[tool.poetry]
name = "pytemplate"
version = "0.1.0"
description = "Template for a Python project"
authors = [
    "SamWarden <SamWardenSad@gmail.com>",
]
maintainers = [
    "SamWarden <SamWardenSad@gmail.com>",
]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/SamWarden/pytemplate"
repository = "https://github.com/SamWarden/pytemplate"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pylint = "^2.15.9"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint]
disable = [
    "C0114",  # Missing module docstrings
    "C0115",  # Missing class docstrings
    "C0116",  # Missing function docstrings
    "R0903",  # Too few public methods
]
max-line-length = 120

[tool.mypy]
python_version = "3.10"
strict = true
pretty = true
disallow_any_explicit = false
disallow_any_generics = false
warn_unreachable = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
