[tool.poetry]
name = "user_service"
version = "1.0.0"
description = "User service example"
authors = [
    "SamWarden <SamWardenSad@gmail.com>",
]
maintainers = [
    "SamWarden <SamWardenSad@gmail.com>",
]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/SamWarden/user_service"
repository = "https://github.com/SamWarden/user_service"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.6"
structlog = "^22.3.0"
fastapi = "^0.94.1"
orjson = "^3.8.7"
alembic = "^1.10.2"
rich = "^13.3.1"
asyncpg = "^0.27.0"
uvicorn = "^0.20.0"
didiator = {version = "^0.3.1", extras = ["di"]}
uuid6 = "^2022.10.25"
aio-pika = "^9.0.5"
uvloop = "^0.17.0"
adaptix = "^3.0.0a1"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"
pytest-asyncio = "^0.20.3"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
pylint = "^2.17.0"
mypy = "^1.1.1"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
