[tool.poetry]
name = "user_service"
version = "0.1.0"
description = "User service example"
authors = [
    "SamWarden <SamWardenSad@gmail.com>",
]
maintainers = [
    "SamWarden <SamWardenSad@gmail.com>",
]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/SamWarden/user_service"
repository = "https://github.com/SamWarden/user_service"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.0rc2"
structlog = "^22.3.0"
fastapi = "^0.89.1"
didiator = {version = "^0.2.0", extras = ["di"]}
uuid7 = "^0.1.0"
orjson = "^3.8.3"
dataclass-factory = {git = "https://github.com/Tishka17/dataclass_factory.git", rev = "925db96970b651a926acfd95b79d34b3b182ec1b"}
alembic = "^1.9.1"
rich = "^13.0.0"
asyncpg = "^0.27.0"
redis = "^4.4.0"
uvicorn = "^0.20.0"

[tool.poetry.group.dev.dependencies]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-asyncio = "^0.20.3"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
pylint = "^2.15.9"
mypy = "^0.991"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
